spring.application.name=springdoc-multi-package
server.address=127.0.0.1
server.port=18080
springdoc.api-docs.version=OPENAPI_3_1
springdoc.api-docs.enabled=true
springdoc.writer-with-order-by-keys=true
spring.servlet.multipart.max-file-size=1MB
spring.servlet.multipart.max-request-size=1MB
